## Pooling BAsics and Implimentation

We are gonna explore pooling and its implie=mentation using Keras. <br><br>

As the word indicates, pooling stands for pooling a bunch of

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import MaxPool2D

2022-12-19 14:39:02.358623: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-19 14:39:02.829927: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-19 14:39:02.830288: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-12-19 14:39:02.887647: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-12-19 14:39:04.530130: W tensorflow/stream_executor/platform/de

In [2]:
image = np.array([[2,2,7,3],
                 [9,4,6,1],
                 [8,5,2,4],
                 [3,1,2,6]],dtype=float)

In [3]:
image.shape

(4, 4)

In [4]:
new_image= image.reshape(1,4,4,1)

In [5]:
model = Sequential([MaxPool2D(pool_size=2, strides=2)])

2022-12-19 14:39:07.953325: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-12-19 14:39:07.954981: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-19 14:39:07.955115: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-12-19 14:39:07.955426: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-12-19 14:39:07.955476: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [6]:
output =  model.predict(new_image)

1/1 [==============================] - 0s 171ms/step


In [7]:
output

array([[[[9.],
         [7.]],

        [[8.],
         [6.]]]], dtype=float32)

In [8]:
output= np.squeeze(output)

In [9]:
output.shape

(2, 2)

In [10]:
output

array([[9., 7.],
       [8., 6.]], dtype=float32)

In [11]:
from keras.layers import AveragePooling2D
model_avg = Sequential(
    [AveragePooling2D(pool_size=2, strides=2)]
)

In [12]:
avg_pool_op = model_avg.predict(new_image)

1/1 [==============================] - 0s 47ms/step


In [13]:
avg_pool_op

array([[[[4.25],
         [4.25]],

        [[4.25],
         [3.5 ]]]], dtype=float32)

In [14]:
avg_pool_op = np.squeeze(avg_pool_op)

In [15]:
avg_pool_op

array([[4.25, 4.25],
       [4.25, 3.5 ]], dtype=float32)